version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE}"

  full-stack:
    build: .
    image: cardsagainsthumanity-full-stack
    ports:
      - "80:4000"
    depends_on:
      - "db"
