version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_DATABASE: "${PGDATABASE}"

  full-stack:
    build: .
    image: cardsagainsthumanity-full-stack
    ports:
      - "80:4000"
    depends_on:
      - "db"
